### PR TITLE
Replace outdated and unmaintained ethdocs.org

### PR DESCRIPTION
**Pull request by sneg55**

### CODE REVIEW

**Comment by sneg55** [comment]
@evertonfraga  Do you mind to take a look?

**Comment by ferrel21** [comment]
Quiero mi dinero

**Comment by alexvandesande** [comment]
Interesting but why ethereum wiki and not the many other good doc sites, like https://docs.ethhub.io/ ? I feel that maybe we should either link to multiple or not at all and it feels like a change that should go in the next website maybe?

**Comment by sneg55** [comment]
> Interesting but why ethereum wiki and not the many other good doc sites, like https://docs.ethhub.io/ ? I feel that maybe we should either link to multiple or not at all and it feels like a change that should go in the next website maybe?

Because ethdocs.org listed under Developer Resources so I thought that https://en.ethereum.wiki/ is the closest replacement for outdated ethdocs. 

I'm also added EthHub under Community resources in updated PR. 

What do you think?   
@alexvandesande

**Pull request closed without merging**
