### PR TITLE
Update Greeter example

### PR DESCRIPTION
**Pull request by erak**
Solidity version 0.5.0 was just released, so the example on https://ethereum.org needs to be updated (the current example will not compile)

Related to: https://github.com/ethereum/ethereum-org/pull/920, https://github.com/ethereum/ethereum-org/pull/921 and https://github.com/ethereum/ethereum-org/pull/922

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

**Review by ekpyron — COMMENTED** [review]
~~There's some usages of ``var`` further down as well I think.~~

**Comment by ekpyron** [comment]
Or is that javascript :-D?

**Review by ekpyron — APPROVED** [review]

**Comment by windyshine** [comment]
x

**Comment by bit-shift** [comment]
Well, test is failing with: ``Fatal error: 403 {"message":"API rate limit exceeded for 35.224.112.202. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}``

Will probably need to trigger this again...

**Review by alexvandesande — APPROVED** [review]

**Review by alexvandesande — APPROVED** [review]

**Pull request merged**
