### PR TITLE
Removed the Ethereum Alarm Clock

### PR DESCRIPTION
**Pull request by chuacw**
Removed the Ethereum Alarm Clock as it is not available on all networks

### CODE REVIEW

**Comment by darkmorpher** [comment]
Related #728

**Comment by alexvandesande** [comment]
Is the alarm clock still running? HAs anyone used it recently?

**Comment by Souptacular** [comment]
@alexvandesande it has recently been updated: https://medium.com/@pipermerriam/ethereum-alarm-clock-reboot-bcfa9106a0d5

**Comment by alexvandesande** [comment]
I'm good with removing it for now. If someone wants to update this part with the new alarm clock feel free.

**Pull request merged**
