### PR TITLE
Removed rb install script and fixed jade include file

### PR DESCRIPTION
**Pull request by cubedro**

### CODE REVIEW

**Comment by alexvandesande** [comment]
This site has changed so much that I think it's better to refork it.

On Mon, Jul 13, 2015 at 9:34 AM, Marian OANCΞA <notifications@github.com>
wrote:

> Merged #18 <https://github.com/ethereum/frontier-release/pull/18>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/frontier-release/pull/18#event-354300003>.
>



-- 

Alex Van de Sande
UX Designer

**Comment by cubedro** [comment]
Are you working on it now? If not it might be good to pull the latest...

**Comment by alexvandesande** [comment]
It might be better if you take a look at the pull request I did on yours.

On Mon, Jul 13, 2015 at 9:48 AM, Marian OANCΞA <notifications@github.com>
wrote:

> Are you working on it now? If not it might be good to pull the latest...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/frontier-release/pull/18#issuecomment-120917937>
> .
>



-- 

Alex Van de Sande
UX Designer

**Comment by alexvandesande** [comment]
https://github.com/alexvandesande/frontier.ethereum.org

**Comment by cubedro** [comment]
but they're different... mine is not a fork... this one has been cloned from mine.

**Comment by alexvandesande** [comment]
So I'm confused that one was a fork from this:
https://github.com/cubedro/frontier.ethereum.org

What's the difference between those?

On Mon, Jul 13, 2015 at 9:54 AM, Marian OANCΞA <notifications@github.com>
wrote:

> but they're different... mine is not a fork... this one has been cloned
> from mine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/frontier-release/pull/18#issuecomment-120919177>
> .
>



-- 

Alex Van de Sande
UX Designer

**Pull request merged**
